server:
  port: 8888

spring:
  application:
    name: proxy
eureka:
  client:
    serviceUrl:
      defaultZone: http://atu:123456@127.0.0.1:8761/eureka/
#修改路由规则
zuul:
  routes:
    userApi:
      path: /home/**
      serviceId: user
      stripPrefix: false
