spring:
  profiles:
    active: prod

adconf:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: 111111

---
spring:
  profiles: dev

server:
  port: 8000

---
spring:
  profiles: test

server:
  port: 8001

---
spring:
  profiles: prod

server:
  port: 8002

