server:
  port: 8761
spring:
  application:
    name: registry
security:
  basic:
    enabled: true
  user:
    name: atu
    password: 111111
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://atu:111111@localhost:${server.port}/eureka/