server:
  port: 9000

spring:
  application:
    name: ad-gateway
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

zuul:
  #访问网关前缀
  prefix: /atu
  #路由信息——针对单个微服而言实现请求转发
  routes:
    sponsor:
      # *————匹配任意数量字符；**————不仅可以匹配任意数量字符，还支持多级目录
      path: /ad-sponsor/**
      serviceId: eureka-client-ad-sponsor
      #跳过前缀
      #127.0.0.1:9000/atu/ad-sponsor/create/adPlan
      #如果是true 则去掉了ad-sponsor，而false是不去掉前缀
      strip-prefix: false

