spring:
  application:
    name: ad-erueka

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    #是否从eureka-server获取注册信息，默认是true
    fetch-registry: false
    #是否将自己注册到eureka-server，默认是true
    register-with-eureka: false
    #eureka-server的地址，默认值是 localhost
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 多节点eureka-server部署
---
#spring:
#  application:
#    name: ad-eureka
#  profiles: server1
#server:
#  port: 8000
#eureka:
#  instance:
#    hostname: server1
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server2:8001/eureka/,http://server3:8002/eureka/
#
#---
#spring:
#  application:
#    name: ad-eureka
#  profiles: server2
#server:
#  port: 8001
#eureka:
#  instance:
#    hostname: server2
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server1:8000/eureka/,http://server3:8002/eureka/
#
#---
#spring:
#  application:
#    name: ad-eureka
#  profiles: server3
#server:
#  port: 8002
#eureka:
#  instance:
#    hostname: server3
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server1:8000/eureka/,http://server2:8001/eureka/
