server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/D812359/code-parent/     # 配置git仓库的地址
          search-paths: spring-cloud-examples/spring-cloud-config-git/config-repo   # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: D812359                                                         # git仓库的账号
          password: Xyz-1995                                                        # git仓库的密码